### ISSUE TITLE
GERD Project TODO

### ISSUE THREAD

**Issue by aerostami** [aerostami/food-logger#5]
- [ ] Get a backup of the database !!
- [ ] Log new Food items into subfolder /foods/ !!
- [ ] Retrieve Foods from /foods/ subfolder in the calendar and homepage !!
- [ ] Unify the old dataset with new data schema
- [ ] Log weight into /weight/
- [ ] Log tags into /tags/ -> tags={tagname, start_time, finish_time}
- [ ] Edit old food logs
- [ ] Voice calories is wrong when loggging with voice. +
- [ ] Yogurt oz calories is not correct +
- [ ] Serving unit problem, greek yogurt is not showing correct amount +
- [ ] Amount overflows the input line +
- [ ] When adding multiple foods in text search, unify image size +
- [ ] Add ADII score +
- [ ] Be able to change amount unit?
